version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: check path
          mapping: |
            alpha_quadrant/.* alpha true
            delta_quadrant/.* delta true
            gamma_quadrant/.* gamma true
          config-path: .circleci/continued_config.yml