version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0
  continuation: circleci/continuation@1.0.0

executors:
  base:
    docker:
      - image: cimg/python:3.8

jobs:
  theme-song:
    executor: base
    parameters:
      json_file:
        type: string
        default: "/tmp/pipeline-parameters.json"
    steps:
      - checkout
      - path-filtering/set-parameters:
          mapping: |
            alpha_quadrant/.* alpha-quadrant true
            delta_quadrant/.* delta-quadrant true
            gamma_quadrant/.* gamma-quadrant true
      - run:
          name: Setup Stand In Workflows
          command: |
            check_and_add_parameter() {
              local file="$1"
              local param_to_check="$2"
              local new_param="$3"

              # Check if the parameter exists in the JSON file
              if ! jq -e ".${param_to_check}" "$file" > /dev/null; then
                # Add the new parameter to the JSON file
                jq --stream-errors --arg "$(new_param)" "true" '. + {($new_param): "true"}' > tmp.json && mv tmp.json "$file"
                echo "Running stand in workflow, added new parameter: $new_param"
              else
                echo "No need to run stand in workflow, parameter $param_to_check already exists"
              fi
            }

            check_and_add_parameter "<< parameters.json_file >>" "alpha-quadrant" "alpha-quadrant-neutral-zone"
            check_and_add_parameter "<< parameters.json_file >>" "delta-quadrant" "delta-quadrant-neutral-zone"
            check_and_add_parameter "<< parameters.json_file >>" "gamma-quadrant" "gamma-quadrant-neutral-zone"

      - continuation/continue:
          parameters: << parameters.json_file >>
          configuration_path: .circleci/continued_config.yml

    

workflows:
  intro-credits:
    jobs:
      - theme-song:
          name: intro credits