version: 2.1

parameters:
  alpha:
    type: boolean
    default: false
  alpha-stand-in:
    type: boolean
    default: false
  delta:
    type: boolean
    default: false
  delta-stand-in:
    type: boolean
    default: false
  gamma:
    type: boolean
    default: false
  gamma-stand-in:
    type: boolean
    default: false

executors:
  base:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  the_job:
    executor: base
    parameters:
      file_path:
        type: string
        default: ""
    steps:
      - checkout
      - run: cat << parameters.file_path >>
  the_stand_in:
    executor: base
    parameters:
      quadrant:
        type: string
        default: ""
    steps:
      - run:
          name: Stand in for << parameters.quadrant >> workflow
          command: |
            echo "Stand in for << parameters.quadrant >> quadrant workflow \n
             marking complete for github checks"

workflows:
  alpha-quadrant:
    when: << pipeline.parameters.alpha >>
    jobs:
      - the_job:
          name: "Setup"
          file_path: alpha_quadrant/wolf_359
      - the_job:
          name: "Unit Tests"
          file_path: alpha_quadrant/wolf_359
          requires:
            - "Setup"
      - the_job:
          name: "Integration Tests"
          file_path: alpha_quadrant/wolf_359
          requires:
            - "Setup"
      - the_job:
          name: "Alpha Workflow Complete"
          file_path: alpha_quadrant/wolf_359
          requires:
            - "Unit Tests"
            - "Integration Tests"
  stand-in-alpha-quadrant:
    when: << pipeline.parameters.alpha-stand-in >>
    jobs:
      - the_stand_in:
          name: "Alpha Workflow Complete"
          quadrant: "alpha"
  delta-quadrant:
    when: << pipeline.parameters.delta >>
    jobs:
      - the_job:
          name: "Setup"
          file_path: delta_quadrant/unicomplex
      - the_job:
          name: "Unit Tests"
          file_path: delta_quadrant/unicomplex
          requires:
            - "Setup"
      - the_job:
          name: "Integration Tests"
          file_path: delta_quadrant/unicomplex
          requires:
            - "Setup"
      - the_job:
          name: "Delta Workflow Complete"
          file_path: delta_quadrant/unicomplex
          requires:
            - "Unit Tests"
            - "Integration Tests"
  stand-in-delta-quadrant:
    when: << pipeline.parameters.delta-stand-in >>
    jobs:
      - the_stand_in:
          name: "Delta Workflow Complete"
          quadrant: "delta"
  gamma-quadrant:
    when: << pipeline.parameters.gamma >>
    jobs:
      - the_job:
          name: "Setup"
          file_path: gamma_quadrant/dominion
      - the_job:
          name: "Unit Tests"
          file_path: gamma_quadrant/dominion
          requires:
            - "Setup"
      - the_job:
          name: "Integration Tests"
          file_path: gamma_quadrant/dominion
          requires:
            - "Setup"
      - the_job:
          name: "Gamma Workflow Complete"
          file_path: gamma_quadrant/dominion
          requires:
            - "Unit Tests"
            - "Integration Tests"
  stand-in-gamma-quadrant:
    when: << pipeline.parameters.gamma-stand-in >>
    jobs:
      - the_stand_in:
          name: "Gamma Workflow Complete"
          quadrant: "gamma"